In [112]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn
%matplotlib inline
pd.options.display.max_rows = 999
pd.options.display.max_columns = 999

## Problem 1: Normalizations Matrix

In [113]:
test_arr = np.array([[1, 2,0],
[0, 1, 1],
[5, 6, 5]])

In [114]:
test_arr

array([[1, 2, 0],
       [0, 1, 1],
       [5, 6, 5]])

In [115]:
import statistics
means = []
stds = []
#statistics.stdev
for i in range(len(test_arr)):
    vals = []
    for j in range(len(test_arr)):
        if test_arr[j,i] !=0:
            vals.append(test_arr[j,i])
    means.append(np.mean(vals))

In [116]:
for i in range(len(test_arr)):
    test_arr[:,i] = [means[i] if item == 0 else item for item in test_arr[:,i]]       

In [117]:
test_arr

array([[1, 2, 3],
       [3, 1, 1],
       [5, 6, 5]])

In [118]:
stds=[]
for i in range(len(test_arr)):
    stds.append(np.std(test_arr[:,i]))

In [119]:
stds

[1.632993161855452, 2.160246899469287, 1.632993161855452]

In [120]:
def normaliser(i,j):
    return(round((test_arr[i,j]-means[i])/stds[i],2))

In [121]:
for i in range(len(test_arr)):
    for j in range(len(test_arr)):
         test_arr[i,j]=normaliser(i,j)

In [123]:
test_arr

array([[-1,  0,  0],
       [ 0,  0,  0],
       [ 1,  1,  1]])

## Problem 2: JSON CLEANING

In [141]:
import json
str_json1 = """{
"id": "1",
"agent": "Radulf Katlego",
"unit": "#3",
"description": "This luxurious studio apartment is in the heart of downtown.",
"num_bedrooms": 1
},
{
"id": "2",
"agent": "Kelemen Konrad",
"unit": "#36",
"description": "We have a 1-bedroom available on the third floor.",
"num_bedrooms": 1
},
{
"id": "3",
"agent": "Ton Jett",
"unit": "#12",
"description": "Beautiful 1-bedroom apartment with nearby yoga studio.",
"num_bedrooms": 1
},
{
"id": "4",
"agent": "Fishel Salman",
"unit": "#13",
"description": "Beautiful studio with a nearby art studio.",
"num_bedrooms": 1
}
}"""
dict_json={}
for i in range(len(str_json.split("},"))):
    dict_json[i]=str_json.split("},")[i]
# = json.loads(str_json)

In [143]:
dict_json[3].split(",")[]

['\n{\n"id": "4"',
 '\n"agent": "Fishel Salman"',
 '\n"unit": "#13"',
 '\n"description": "Beautiful studio with a nearby art studio."',
 '\n"num_bedrooms": 1\n}\n}']

In [160]:
def finder_st(x):
    x = str.lower(x)
    return([x.find('studio'),x.find('1-bedroom'),x.find('yoga'),x.find('dance'),x.find('art')])

In [187]:
def finder_st(x):
    x = str.lower(x)
    chk = [x.find('studio'),x.find('1-bedroom'),x.find('yoga'),x.find('dance'),x.find('art')]
    min_value =min(chk)
    if (sum([chk[2],chk[3],chk[4]])<=0):
        if min_value == chk[0] or chk[0]<chk[1]:
            return(0)
        if min_value == chk[1] or chk[1]<chk[0]:
            return(1)
    elif min_value == chk[0] and chk[0]<min([chk[2],chk[3],chk[4]]):
            return(0)
    elif min_value == chk[1] and chk[1]<min([chk[2],chk[3],chk[4]]):
            return(1)
   

In [188]:
for i in range(len(dict_json)):
    for j in dict_json[i].split(","):
        if("num_bedrooms") in j:
            fix = j[-1]
        if ("description" in j):
            print(finder_st(j))
    

None
0
None
None


In [170]:
for i in range(len(dict_json)):
    for j in dict_json[i].split(","):
        if ("description" in j):
            print(j)


"description": "This luxurious studio apartment is in the heart of downtown."

"description": "We have a 1-bedroom available on the third floor."

"description": "Beautiful 1-bedroom apartment with nearby yoga studio."

"description": "Beautiful studio with a nearby art studio."
